version: "3.9"
services:
  slam_debug:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      args:
        - BASE_IMAGE=ubuntu:22.04
        - GTSAM_VERSION=4.2.0
        - USERNAME=${USERNAME:-developer}
        - UID=${UID}
        - GID=${GID}
    container_name: slam_debug
    image: slam_debug:devel
    network_mode: "host"
    tty: true
    volumes:
      - ..:/home/${USERNAME}/git/slam_debug

